name: "Release & Publish"

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'The type of release to be performed'
        default: 'patch'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      shell: bash
      run: pip install poetry && poetry config virtualenvs.create false --local
    - name: Install dependencies
      run: |
        python -m poetry install
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest -v tests

  publish:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
