name: "Release & Publish"

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'The type of release to be performed'
        default: 'patch'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      shell: bash
      run: pip install poetry && poetry config virtualenvs.create false --local
    - name: Install dependencies
      run: |
        python -m poetry install
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest -v tests

  publish:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          additional_options: --${{ github.event.inputs.bumpType }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
